from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
style = doc.styles['Normal']
style.font.name = 'Times New Roman'
style.font.size = Pt(11)

SHOTS = "C:/Users/User/Downloads/lab3/screenshots"

# ============ COVER PAGE ============
for _ in range(6):
    doc.add_paragraph('')
t = doc.add_paragraph()
t.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = t.add_run('Comp 4322 Internetworking Protocols, Software and Management')
r.bold = True; r.font.size = Pt(16)
t2 = doc.add_paragraph()
t2.alignment = WD_ALIGN_PARAGRAPH.CENTER
r2 = t2.add_run('Lab 3: IP & ICMP')
r2.bold = True; r2.font.size = Pt(14)
for _ in range(3):
    doc.add_paragraph('')
info = doc.add_paragraph()
info.alignment = WD_ALIGN_PARAGRAPH.CENTER
info.add_run('Student Name: Cheng Wui Sum\nStudent ID: 22074221d\nDue: 11:59pm, April 8, 2026').font.size = Pt(12)
doc.add_page_break()

def add_img(path, width=6.2):
    doc.add_picture(path, width=Inches(width))

# ============ IP SECTION ============
doc.add_heading('IP', level=1)

# --- Q3 ---
doc.add_heading('Q3', level=2)
p = doc.add_paragraph()
p.add_run('How many bytes are in the IP header? How many bytes are in the payload of the IP datagram? Explain how you determined the number of payload bytes.').italic = True

add_img(f"{SHOTS}/ip_q3_56byte.png")
doc.add_paragraph(
    'The IP header is 20 bytes long, indicated by the Header Length field: IHL = 5 (5 × 4 = 20 bytes). '
    'The IP payload is 64 bytes, calculated as: Total Length (84) − Header Length (20) = 64 bytes. '
    'The 64-byte payload consists of the 8-byte ICMP header (Type, Code, Checksum, Identifier, Sequence Number) '
    'plus 56 bytes of ICMP data ("abcdefghijklmnop..." padding).'
)

# --- Q5 ---
doc.add_heading('Q5', level=2)
p = doc.add_paragraph()
p.add_run('Which fields in the IP datagram always change from one datagram to the next within this series of ICMP messages sent by your computer?').italic = True

add_img(f"{SHOTS}/ip_q5_q7_id_pattern.png")
doc.add_paragraph(
    'The fields that always change are:\n'
    '1. Identification — increments by 1 each packet (0x0b71, 0x0b72, 0x0b73, ..., 0x0b7a)\n'
    '2. Header Checksum — recomputed for each datagram since the Identification field changed\n\n'
    'Fields that stay constant: Version (4), Header Length (20), DSCP (0x00), Total Length (60), '
    'Flags (0x00), Fragment Offset (0), TTL (128), Protocol (ICMP/1), Source IP (192.168.68.75), '
    'Destination IP (143.89.209.9). The constant fields must stay the same because they describe '
    'the same type of packet to the same destination. The Identification and Checksum must change '
    'because each datagram needs a unique ID for reassembly, and the checksum covers the header.'
)

# --- Q7 ---
doc.add_heading('Q7', level=2)
p = doc.add_paragraph()
p.add_run('Describe the pattern you see in the values in the Identification field of the IP datagram.').italic = True

doc.add_paragraph(
    'As shown in the screenshot above, the Identification field increments sequentially by exactly 1 '
    'for each successive ICMP Echo Request: 0x0b71 (2929), 0x0b72 (2930), 0x0b73 (2931), ..., '
    '0x0b7a (2938). This is the standard behavior of the Windows IP stack, which uses a simple '
    'incrementing global counter for the Identification field.'
)

# --- Q9 ---
doc.add_heading('Q9', level=2)
p = doc.add_paragraph()
p.add_run('Do these values remain unchanged for all of the ICMP TTL-exceeded replies sent to your computer by the nearest (first hop) router? Why?').italic = True

add_img(f"{SHOTS}/ip_q9_first_hop.png")
doc.add_paragraph(
    'The three TTL-exceeded replies from the first-hop router (192.168.68.1) show:\n'
    '• TTL: constant at 64 for all three replies. This is expected — the router is one hop away and uses '
    'a default TTL of 64.\n'
    '• Identification: changes between replies (0x1f50, 0x1f54, 0x1f57). This is expected because each '
    'ICMP TTL-exceeded reply is a new IP datagram generated by the router with its own incrementing '
    'Identification counter. The values are not strictly sequential because the router sends other '
    'IP datagrams between these replies.'
)

# --- Q11 ---
doc.add_heading('Q11', level=2)
p = doc.add_paragraph()
p.add_run(
    'Print out the first fragment of the fragmented IP datagram. What information in the IP header '
    'indicates that the datagram has been fragmented? What information in the IP header indicates '
    'whether this is the first fragment versus a latter fragment? How long is this IP datagram?'
).italic = True

add_img(f"{SHOTS}/ip_q11_first_fragment.png")
doc.add_paragraph(
    'First fragment (Frame 1337) of the 2000-byte ICMP Echo Request:\n'
    '• Total Length: 1500 bytes\n'
    '• Identification: 0xdab6\n'
    '• Flags: More Fragments (MF) = 1 — this indicates the datagram HAS been fragmented.\n'
    '• Fragment Offset: 0 — this indicates it is the FIRST fragment.\n\n'
    'How to distinguish first vs. latter fragments:\n'
    '• First fragment: MF = 1, Offset = 0\n'
    '• Latter fragment: Offset > 0 (MF = 1 if more follow, MF = 0 if last)\n\n'
    'This IP datagram is 1500 bytes long (maximum Ethernet MTU).'
)

add_img(f"{SHOTS}/ip_q11_second_fragment.png")
doc.add_paragraph(
    'Second/last fragment (Frame 1338):\n'
    '• Total Length: 548 bytes, MF = 0 (no more fragments), Offset = 1480\n'
    '• Same Identification 0xdab6 confirms it belongs to the same original datagram.\n'
    '• Offset > 0 indicates this is NOT the first fragment. MF = 0 indicates it is the last.\n'
    '• Reassembled total: 1480 + 528 = 2008 bytes (20 IP header + 8 ICMP header + 2000 data - 20 = 2008 payload).'
)

# --- Q15 ---
doc.add_heading('Q15', level=2)
p = doc.add_paragraph()
p.add_run('What fields change in the IP header among the fragments?').italic = True

add_img(f"{SHOTS}/ip_q15_3500_fragments.png")
doc.add_paragraph(
    'The 3500-byte ICMP Echo Request is fragmented into 3 IP datagrams (ID = 0xdabb):\n\n'
    'Fragment 1: Total Length = 1500, MF = 1, Offset = 0\n'
    'Fragment 2: Total Length = 1500, MF = 1, Offset = 1480\n'
    'Fragment 3: Total Length = 568,  MF = 0, Offset = 2960\n\n'
    'Fields that CHANGE among fragments:\n'
    '1. Total Length — 1500, 1500, 568\n'
    '2. More Fragments (MF) flag — 1, 1, 0\n'
    '3. Fragment Offset — 0, 1480, 2960\n'
    '4. Header Checksum — recomputed for each fragment\n\n'
    'Fields that stay the SAME: Version, IHL, DSCP, Identification (0xdabb), TTL (128), '
    'Protocol (ICMP/1), Source IP, Destination IP. The Identification must stay the same '
    'so the receiver can reassemble the fragments.'
)

doc.add_page_break()

# ============ ICMP SECTION ============
doc.add_heading('ICMP', level=1)

# --- Q1 ---
doc.add_heading('Q1', level=2)
p = doc.add_paragraph()
p.add_run('What is the IP address of your host? What is the IP address of the destination host?').italic = True

add_img(f"{SHOTS}/icmp_q1_q3_ping_request.png")
doc.add_paragraph(
    'From the first ICMP Echo Request (Frame 579) in the ping capture:\n'
    '• My host IP address: 192.168.68.75\n'
    '• Destination host IP address: 143.89.209.9 (www.ust.hk)\n\n'
    'My host uses a private IP address (192.168.68.0/22 subnet) behind a NAT router (TP-Link, 192.168.68.1).'
)

# --- Q3 ---
doc.add_heading('Q3', level=2)
p = doc.add_paragraph()
p.add_run(
    'Examine one of the ping request packets sent by your host. What are the ICMP type and code numbers? '
    'What other fields does this ICMP packet have? How many bytes are the checksum, sequence number '
    'and identifier fields?'
).italic = True

add_img(f"{SHOTS}/icmp_q3_ping_reply.png")
doc.add_paragraph(
    'Ping Echo Request (Frame 579):\n'
    '• Type: 8 (Echo Request)\n'
    '• Code: 0\n\n'
    'Other fields:\n'
    '• Checksum: 0x010b — 2 bytes (16 bits)\n'
    '• Identifier: 0x0007 — 2 bytes (16 bits)\n'
    '• Sequence Number: 19530 (0x4c4a) — 2 bytes (16 bits)\n'
    '• Data: 32 bytes of padding ("abcdefghijklmnop...")\n\n'
    'Corresponding Echo Reply (Frame 580):\n'
    '• Type: 0 (Echo Reply), Code: 0\n'
    '• Checksum: 0x090b (2 bytes), Identifier: 0x0007 (2 bytes), Sequence: 19530 (2 bytes)\n'
    '• The reply contains the same Identifier, Sequence Number, and Data as the request.'
)

# --- Q7 ---
doc.add_heading('Q7', level=2)
p = doc.add_paragraph()
p.add_run(
    'Examine the ICMP echo packet in your screenshot. Is this different from the ICMP ping query '
    'packets in the first half of this lab? If yes, how so?'
).italic = True

add_img(f"{SHOTS}/icmp_q7_tracert_echo.png")
doc.add_paragraph(
    'The tracert ICMP Echo Request (Frame 115) differs from the ping Echo Request:\n\n'
    '1. TTL: Tracert sets TTL = 1 (incrementing per hop), while ping uses TTL = 128 (Windows default). '
    'This is the fundamental difference — tracert uses low TTL values to discover intermediate routers.\n'
    '2. Data size: Tracert carries 64 bytes of all-zero padding; ping carries 32 bytes of "abcdefgh..." padding.\n'
    '3. IP Total Length: Tracert = 92 bytes (20 IP + 8 ICMP + 64 data); Ping = 60 bytes (20 + 8 + 32).\n\n'
    'Similarities: Both use Type 8 (Echo Request), Code 0, and have the same ICMP fields '
    '(Checksum, Identifier, Sequence Number).'
)

# --- Q9 ---
doc.add_heading('Q9', level=2)
p = doc.add_paragraph()
p.add_run(
    'Examine the last three ICMP packets received by the source host. How are these packets different '
    'from the ICMP error packets? Why are they different?'
).italic = True

add_img(f"{SHOTS}/icmp_q9_ttl_exceeded.png")
add_img(f"{SHOTS}/icmp_q9_last_packets.png")
doc.add_paragraph(
    'The last three ICMP packets received are TTL-exceeded (Type 11, Code 0) messages from the 9th hop '
    'router (213.144.183.207). In our trace, the tracert to www.inria.fr did not fully complete.\n\n'
    'In a complete tracert, the last three packets would be Echo Reply (Type 0, Code 0) from the '
    'destination host (128.93.162.83) rather than TTL-exceeded errors from intermediate routers.\n\n'
    'Key differences between Echo Reply and TTL-exceeded:\n'
    '1. Type: Echo Reply = Type 0; TTL-exceeded = Type 11\n'
    '2. Source IP: Echo Reply comes from the destination; TTL-exceeded comes from intermediate routers\n'
    '3. Payload: TTL-exceeded packets contain the original IP header + first 8 bytes of the triggering '
    'packet (encapsulated). Echo Reply simply echoes back the original data.\n'
    '4. Why different: The last-hop probes reach the destination without TTL expiring, so the destination '
    'responds with an Echo Reply instead of a router dropping the packet.'
)

# Save
out = 'C:/Users/User/Downloads/lab3/Lab3_Report_Cheng Wui Sum_22074221D.docx'
doc.save(out)
print(f'Report saved: {out}')
